name: 'Get chart details'
description: 'Returns key details of the specified Helm chart'
inputs:
  path:
    description: 'Local path to the Helm chart directory'
    required: true
  allowChartToNotExist:
    description: 'Allow Chart.yaml to not be present'
    required: false
    default: 'false'
  validateChartYaml:
    description: 'Should Chart.yaml be validated'
    required: false
    default: 'true'
  requireChangelog:
    description:
      'Should Chart.yaml validation check for presence of a changelog'
    required: false
    default: 'true'
outputs:
  name:
    description: 'Chart name'
  version:
    description: 'Chart version'
  type:
    description: 'Chart type'
  changes:
    description: 'JSON representation of chart changelog (if any)'
runs:
  using: 'node20'
  main: '../dist/get-chart-details.js'
