---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name (e.g. v1.0.0)
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: main
          token: ${{ secrets.FORGEJO_TOKEN }}

      - name: Create and push tag
        env:
          TAG: ${{ inputs.tag }}
          CI_TAG_AUTHOR: lab-assistant
          CI_TAG_EMAIL: lab-assistant@git.bjw-s.dev
        run: |-
          git config --local user.email "${{ env.CI_TAG_EMAIL }}"
          git config --local user.name "${{ env.CI_TAG_AUTHOR }}"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Create Forgejo release
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
          TAG: ${{ inputs.tag }}
        run: |-
          jq -n \
            --arg tag_name "$TAG" \
            '{tag_name: $tag_name, name: $tag_name}' \
          | curl -sS -X POST \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases" \
            -H "Authorization: token $FORGEJO_TOKEN" \
            -H "Content-Type: application/json" \
            -d @-

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.gh_mirror_token }}
          TAG: ${{ inputs.tag }}
        run: |-
          jq -n \
            --arg tag_name "$TAG" \
            '{tag_name: $tag_name, name: $tag_name}' \
          | curl -sS -X POST \
            "https://api.github.com/repos/bjw-s-labs/helm-charts-actions/releases" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -d @-
