---
name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        id: npm-ci
        run: |
          pnpm run ci

      - name: Check Format
        id: npm-format-check
        run: pnpm run format:check

      - name: Lint
        id: npm-lint
        run: pnpm run lint

      - name: Test
        id: npm-ci-test
        run: pnpm run ci-test
