---
name: Lint Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        id: install
        run: |
          pnpm run ci

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: (dist/.*|pnpm-lock\.yaml)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: '.'
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_GIT_COMMITLINT: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JSCPD: false
          VALIDATE_JSONC: false ## disable until v7.4.0
          VALIDATE_JSON: false
          VALIDATE_TYPESCRIPT_ES: false
